2018-04-25 11:12:59|ERROR|Home.profitList|PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-50,50' at line 1 in /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/NotORM/NotORM/Result.php:240
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/NotORM/NotORM/Result.php(877): NotORM_Result->query('select sum(r.to...', Array)
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/NotORM/NotORM/Result.php(868): NotORM_Result->queryRows('select sum(r.to...', Array)
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Model/Home.php(341): NotORM_Result->queryAll('select sum(r.to...')
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Domain/Home.php(79): Model_Home->profitList('19211', 'total', '0')
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Home.php(407): Domain_Home->profitList('19211', 'total', '0')
#5 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(57): Api_Home->profitList()
#6 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#7 {main}
2018-04-25 17:04:19|ERROR|Home.profitList|PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-50,50' at line 1 in /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/NotORM/NotORM/Result.php:240
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/NotORM/NotORM/Result.php(877): NotORM_Result->query('select sum(r.to...', Array)
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/NotORM/NotORM/Result.php(868): NotORM_Result->queryRows('select sum(r.to...', Array)
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Model/Home.php(341): NotORM_Result->queryAll('select sum(r.to...')
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Domain/Home.php(79): Model_Home->profitList('19211', 'total', '0')
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Home.php(407): Domain_Home->profitList('19211', 'total', '0')
#5 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(57): Api_Home->profitList()
#6 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#7 {main}
2018-04-25 20:12:00|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:20|ERROR|User.iftoken|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:21|ERROR|Home.getConfig|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:21|ERROR|User.Bonus|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:21|ERROR|User.getBaseInfo|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:21|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:25|ERROR|Live.createRoom|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:28|ERROR|Live.createRoom|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:29|ERROR|Live.createRoom|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:30|ERROR|Live.createRoom|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:30|ERROR|Live.createRoom|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:30|ERROR|Live.createRoom|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:31|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:32|ERROR|Home.getFollow|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:33|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:33|ERROR|Home.getFollow|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:34|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:34|ERROR|Home.getNew|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:34|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:34|ERROR|Home.getFollow|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:35|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:35|ERROR|Home.getNew|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:36|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:36|ERROR|Home.getFollow|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
2018-04-25 20:13:36|ERROR|Home.getHot|RedisException: Connection refused in /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php:13
Stack trace:
#0 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(13): Redis->pconnect('127.0.0.1', '6379')
#1 /data/wwwroot/livenew.yunbaozhibo.com/api/Appapi/Api/Common.php(5): Api_Common->connectionRedis()
#2 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi/ApiFactory.php(57): Api_Common->__construct()
#3 /data/wwwroot/livenew.yunbaozhibo.com/api/PhalApi/PhalApi.php(55): PhalApi_ApiFactory::generateService()
#4 /data/wwwroot/livenew.yunbaozhibo.com/api/public/index.php(14): PhalApi->response()
#5 {main}
